services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Framework\Config\Ui\Fields\:
        resource: '../../Ui/Fields/*'
        tags:
            - {name: 'expansion.config.ui'}

    eXpansion\Framework\Config\Ui\Fields\TextField:
        class: eXpansion\Framework\Config\Ui\Fields\TextField
        tags:
            - {name: 'expansion.config.ui', priority: -1}

    eXpansion\Framework\Config\Ui\Window\ConfigWindowFactory:
        class: eXpansion\Framework\Config\Ui\Window\ConfigWindowFactory
        arguments:
            $name: "Configuration"
            $sizeX : 128
            $sizeY : 120