services:
    eXpansion\Bundle\WidgetCurrentMap\Plugins\WidgetCurrentMap:
        class: eXpansion\Bundle\WidgetCurrentMap\Plugins\WidgetCurrentMap
        autowire: true
        arguments:
                $players: '@expansion.framework.core.user_groups.all_players'
        tags:
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}
          - {name: 'expansion.plugin', data_provider: 'exp.mapratings'}

    eXpansion\Bundle\WidgetCurrentMap\Plugins\Gui\CurrentMapWidgetFactory:
            class: eXpansion\Bundle\WidgetCurrentMap\Plugins\Gui\CurrentMapWidgetFactory
            autowire: true
            arguments:
                $name:  "Current Map"
                $posX: 0
                $posY: 0
                $sizeX: null
                $sizeY: null
            tags:
                - {name: expansion.plugin, data_provider: exp.widget }