services:
    expansion.bundle.liverankings.data_providers.compatibility.tm:
        class: eXpansion\Framework\Core\DataProviders\EmptyDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "exp.live_rankings.tm", interface: eXpansion\Framework\Core\Plugins\StatusAwarePluginInterface}
            - {name: expansion.dataprovider.compatibility, title: 'TM'}

    eXpansionExperimantal\Bundle\WidgetLiveRankings\Plugins\LiveRankings:
        class:  eXpansionExperimantal\Bundle\WidgetLiveRankings\Plugins\LiveRankings
        autowire: true
        arguments:
                $players: '@expansion.framework.core.user_groups.players'
                $allPlayers: '@expansion.framework.core.user_groups.all_players'
        tags:
          - {name: 'expansion.plugin', data_provider: 'exp.live_rankings.tm'}

    eXpansionExperimantal\Bundle\WidgetLiveRankings\Plugins\Gui\LiveRankingsWidgetFactory:
            class: eXpansionExperimantal\Bundle\WidgetLiveRankings\Plugins\Gui\LiveRankingsWidgetFactory
            autowire: true
            arguments:
                $name:  "LiveRankings"
                $posX: 0
                $posY: 0
                $sizeX: null
                $sizeY: null
            tags:
              - {name: expansion.plugin, data_provider: exp.widget}