<?php

namespace eXpansion\Framework\PlayersBundle\Repository;

use eXpansion\Framework\PlayersBundle\Entity\Player;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $login Login of the player to laod.
     *
     * @return Player|null
     */
    public function findByLogin($login)
    {
        $player = $this->findOneBy(['login' => $login]);
        return $player;
    }

    /**
     * Save player data in database.
     *
     * @param Player[] $players
     */
    public function save(array $players)
    {
        if (empty($players)) {
            return;
        }

        foreach ($players as $player) {
            $this->getEntityManager()->persist($player);
        }

        $this->getEntityManager()->clear();
        $this->getEntityManager()->flush();
    }
}
