<?php

namespace eXpansion\Framework\PlayersBundle\Repository;

use Doctrine\ORM\EntityRepository;
use eXpansion\Framework\PlayersBundle\Entity\Player;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    /**
     * @param string $login Login of the player to load.
     *
     * @return Player|null
     */
    public function findByLogin($login)
    {
        $player = $this->findOneBy(['login' => $login]);

        return $player;
    }

    /**
     * Save player data in database.
     *
     * @param Player[] $players
     */
    public function save(array $players)
    {
        if (empty($players)) {
            return;
        }

        foreach ($players as $player) {
            var_dump($player->getId());
            $player = $this->getEntityManager()->merge($player);
            $this->getEntityManager()->persist($player);
        }

        $this->getEntityManager()->flush();
    }
}
