services:
    _defaults:
        autowire: true
        autoconfigure: true

    eXpansion.local_records.config.nb_records:
        class: eXpansion\Framework\Config\Model\IntegerConfig
        arguments:
            $path: "eXpansion/LocalRecords/NbRecords"
            $name: "expansion_local_records.config.nb_records.name"
            $scope: "global"
            $description: "expansion_local_records.config.nb_records.dsc"
            $defaultValue: 100
            $minValue: 10
            $maxValue: 10000
        tags:
            - {name: expansion.config}

    eXpansion.local_records.config.notification_public_threshold:
        class: eXpansion\Framework\Config\Model\IntegerConfig
        arguments:
            $path: "eXpansion/LocalRecords/NotificationPublicThreshold"
            $name: "expansion_local_records.config.notification_public_threshold.name"
            $scope: "global"
            $description: "expansion_local_records.config.notification_public_threshold.dsc"
            $defaultValue: 20
            $maxValue: 100
            $minValue: 0
        tags:
            - {name: expansion.config}

    eXpansion.local_records.config.color_codes.record:
        class: eXpansion\Framework\Config\Model\ChatColorCodeConfig
        arguments:
            $path: "%expansion.core.config.path.color_codes%/record"
            $scope: "key"
            $name: "expansion_local_records.config.color_codes.record"
            $description: ""
            $defaultValue: "$0f3"
        tags:
            - {name: expansion.config}

    eXpansion.local_records.config.color_codes.record_top:
        class: eXpansion\Framework\Config\Model\ChatColorCodeConfig
        arguments:
            $path: "%expansion.core.config.path.color_codes%/record_top"
            $scope: "key"
            $name: "expansion_local_records.config.color_codes.record_top"
            $description: ""
            $defaultValue: "$0d3"
        tags:
            - {name: expansion.config}

    eXpansion.local_records.config.color_codes.record_rank:
        class: eXpansion\Framework\Config\Model\ChatColorCodeConfig
        arguments:
            $path: "%expansion.core.config.path.color_codes%/record_rank"
            $scope: "key"
            $name: "expansion_local_records.config.color_codes.record_rank"
            $description: ""
            $defaultValue: "$afa"
        tags:
            - {name: expansion.config}

    eXpansion.local_records.config.glyph_icon.time:
        class: eXpansion\Framework\Config\Model\TextConfig
        arguments:
            $path: "%expansion.core.config.path.glymp_icons%/time"
            $scope: "key"
            $name: "expansion_local_records.config.glymp_icons.time"
            $description: ""
            $defaultValue: ''
        tags:
            - {name: expansion.config}

    eXpansion.local_records.config.glyph_icon.record:
        class: eXpansion\Framework\Config\Model\TextConfig
        arguments:
            $path: "%expansion.core.config.path.glymp_icons%/record"
            $scope: "key"
            $name: "expansion_local_records.config.glymp_icons.record"
            $description: ""
            $defaultValue: ''
        tags:
            - {name: expansion.config}