
services:
    _defaults:
        autowire: true
        public: true

    #
    # Services used to handle records for individual laps.
    #
    eXpansion.local_records.services.lap_record_handler_factory:
        class: eXpansion\Bundle\LocalRecords\Services\RecordHandlerFactory
        arguments:
            $ordering: ASC
            $nbRecords: '@eXpansion.local_records.config.nb_records'

    # Plugins to save lap records in all TM gamemodes.
    expansion.local_records.plugins.lap_records:
        class: eXpansion\Bundle\LocalRecords\Plugins\LapsRecords
        arguments:
            $recordsHandlerFactory: '@eXpansion.local_records.services.lap_record_handler_factory'
            $allPlayersGroup: '@expansion.framework.core.user_groups.all_players'
            $eventPrefix: 'expansion.local_records.lap'
        tags:
            - {name: 'expansion.plugin', data_provider: 'mp.legacy.player'}
            - {name: 'expansion.plugin', data_provider: 'mp.script.map'}
            - {name: 'expansion.plugin', data_provider: 'mp.script.match'}
            - {name: 'expansion.plugin', data_provider: 'tm.script.lap'}

    # Data provider to lap records data to other plugins.
    eXpansion.local_records.data_providers.lap_records:
        class: eXpansion\Bundle\LocalRecords\DataProviders\RecordsDataProvider
        tags:
          - {name: 'expansion.dataprovider', provider: "expansion.local_records.lap", interface: 'eXpansion\Bundle\LocalRecords\DataProviders\Listener\RecordsDataListener'}
          - {name: 'expansion.dataprovider.compatibility', title: 'ALL'}
          - {name: 'expansion.dataprovider.parent', parent: 'expansion.local_records.plugins.lap_records'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.local_records.lap.loaded', method: 'onRecordsLoaded'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.local_records.lap.first_time', method: 'onFirstRecord'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.local_records.lap.same_score', method: 'onSameScore'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.local_records.lap.same_position', method: 'onSamePosition'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.local_records.lap.better_position', method: 'onBetterPosition'}

    # Plugin to have chat notificaiton for lap records.
    eXpansion.local_records.plugins.lap_records_notifications:
        class: eXpansion\Bundle\LocalRecords\Plugins\ChatNotification
        arguments:
            $translationPrefix: 'expansion_local_records.chat.lap'
            $positionForPublicMessage: '@eXpansion.local_records.config.notification_public_threshold'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.local_records.lap'}
