services:
    _defaults:
        autowire: true
        public: true

    eXpansion\Bundle\LocalRecords\Model\RecordQueryBuilder:
        class: eXpansion\Bundle\LocalRecords\Model\RecordQueryBuilder

    eXpansion\Bundle\LocalRecords\Plugins\AllRecords:
        class: eXpansion\Bundle\LocalRecords\Plugins\AllRecords
        tags:
          - {name: 'expansion.plugin', data_provider: 'expansion.local_records.race|expansion.local_records.lap'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}


    eXpansion\Bundle\LocalRecords\Plugins\MenuItems:
        class: eXpansion\Bundle\LocalRecords\Plugins\MenuItems
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.menu.items'}
