services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    eXpansion\Framework\AdminGroups\Services\AdminGroupConfiguration:
        class: eXpansion\Framework\AdminGroups\Services\AdminGroupConfiguration
        arguments:
            $path: '%expansion.admin_groups.config.path%'
