parameters:
    expansion.framework.core.model.gui.manialink.class: 'eXpansion\Framework\Core\Model\Gui\Manialink'
    expansion.framework.core.model.gui.window.class: 'eXpansion\Framework\Core\Model\Gui\Window'
    expansion.framework.core.model.gui.widget.class: 'eXpansion\Framework\Core\Model\Gui\Widget'
    expansion.framework.core.model.gui.fml_manialink.class: 'eXpansion\Framework\Core\Model\Gui\FmlManialink'
    expansion.framework.core.model.gui.action.class: 'eXpansion\Framework\Core\Model\Gui\Action'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # GUI Contexes to put everything together.
    #
    eXpansion\Framework\Core\Model\Gui\ManialinkFactoryContext:
        class: 'eXpansion\Framework\Core\Model\Gui\ManialinkFactoryContext'
        arguments:
            $className: "%expansion.framework.core.model.gui.manialink.class%"

    eXpansion\Framework\Core\Model\Gui\WidgetFactoryContext:
        class: 'eXpansion\Framework\Core\Model\Gui\WidgetFactoryContext'
        arguments:
            $className: "%expansion.framework.core.model.gui.widget.class%"

    eXpansion\Framework\Core\Model\Gui\WindowFactoryContext:
        class: eXpansion\Framework\Core\Model\Gui\WindowFactoryContext
        arguments:
            $className: "%expansion.framework.core.model.gui.window.class%"

    eXpansion\Framework\Core\Model\Gui\FmlManialinkFactoryContext:
           class: eXpansion\Framework\Core\Model\Gui\FmlManialinkFactoryContext
           arguments:
               $className: "%expansion.framework.core.model.gui.fml_manialink.class%"
    #
    # GUI Element factories
    #
    eXpansion\Framework\Core\Model\Gui\Factory\:
            resource: '../../Model/Gui/Factory/*'

    expansion.framework.core.gui.element.factory.title_line:
        class: 'eXpansion\Framework\Core\Model\Gui\Factory\LineFactory'
        arguments:
            $type: 'title'

    eXpansion\Framework\Core\Model\Gui\Factory\WindowFrameFactory:
        class: eXpansion\Framework\Core\Model\Gui\Factory\WindowFrameFactory
        arguments:
          $maniaScriptFactory: '@expansion.framework.core.maniascript.window'

    eXpansion\Framework\Core\Model\Gui\Factory\WidgetFrameFactory:
        class: eXpansion\Framework\Core\Model\Gui\Factory\WidgetFrameFactory
        arguments:
          $maniaScriptFactory: '@expansion.framework.core.maniascript.widget'

    eXpansion\Framework\Core\Model\Gui\Factory\WindowFrameFactoryInterface: '@eXpansion\Framework\Core\Model\Gui\Factory\WindowFrameFactory'


    #
    # Default window factories.
    #
    eXpansion\Framework\Core\Plugins\Gui\WindowHelpFactory:
        class: 'eXpansion\Framework\Core\Plugins\Gui\WindowHelpFactory'
        arguments:
            $name:  'expansion_core.windows.chat_commands.title'
            $sizeX: 180
            $sizeY: 90
            $posX:  null
            $posY:  null
            $dataCollectionFactory: "@expansion.gui.gridbuilder.datacollection.array"

    eXpansion\Framework\Core\Plugins\Gui\WindowHelpDetailsFactory:
        class: 'eXpansion\Framework\Core\Plugins\Gui\WindowHelpDetailsFactory'
        arguments:
            $name: 'expansion_core.windows.chat_commands_description.title'
            $sizeX: 180
            $sizeY: 90
            $posX: null
            $posY: null
