parameters:

services:
    eXpansion\Framework\Core\Listener\BaseStorageUpdateListener:
        class: 'eXpansion\Framework\Core\Listener\BaseStorageUpdateListener'
        autowire: true
        tags:
            - { name: kernel.event_listener, event: maniaplanet.game.BeginMap }
            - { name: kernel.event_listener, event: maniaplanet.game.expansion.after_init }
