services:
    eXpansion\Framework\Core\Listener\BaseStorageUpdateListener:
        class: eXpansion\Framework\Core\Listener\BaseStorageUpdateListener
        autowire: true
        public: true
        autoconfigure: true
        tags:
            - { name: kernel.event_subscriber }
