services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true


    #
    # Plugin to send analytics data to eXpansion master server.
    #
    eXpansion\Framework\Core\Plugins\Analytics:
        class: 'eXpansion\Framework\Core\Plugins\Analytics'
        arguments:
            $handshakeUrl: 'https://mp-expansion.com/api/expansion/analytics/handshake'
            $pingUrl: 'https://mp-expansion.com/api/expansion/analytics/ping'
            $pingInterval: 600
            $retryInterval: 14400
        tags:
            - {name: expansion.plugin, data_provider: exp.timer}

