parameters:
    expansion.service.dedicated_connection.class: Maniaplanet\DedicatedServer\Connection
    expansion.service.dedicated_connection.factory.class: eXpansion\Framework\Core\Services\DedicatedConnection\Factory
    expansion.service.application.class: eXpansion\Framework\Core\Services\Application
    expansion.service.plugin_manager.class: eXpansion\Framework\Core\Services\PluginManager
    expansion.service.data_provider_manager.class: eXpansion\Framework\Core\Services\DataProviderManager
    expansion.service.console.class: eXpansion\Framework\Core\Services\Console
    expansion.service.chat_commands.class: eXpansion\Framework\Core\Services\ChatCommands
    expansion.service.chat_commands.depth: 3

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    expansion.service.dedicated_connection.factory:
        class: "%expansion.service.dedicated_connection.factory.class%"
        arguments:
            - "%dedicated_host%"
            - "%dedicated_port%"
            - "%dedicated_timeout%"
            - "%dedicated_user%"
            - "%dedicated_password%"

    expansion.service.dedicated_connection:
        class: "%expansion.service.dedicated_connection.class%"
        factory: "expansion.service.dedicated_connection.factory:createConnection"
    Maniaplanet\DedicatedServer\Connection: "@expansion.service.dedicated_connection"

    eXpansion\Framework\Core\Services\Application:
        class: "%expansion.service.application.class%"

    eXpansion\Framework\Core\Services\ApplicationDebug:
        class: eXpansion\Framework\Core\Services\ApplicationDebug

    eXpansion\Framework\Core\Services\Application\Dispatcher:
        class: eXpansion\Framework\Core\Services\Application\Dispatcher
        calls:
            - [addEventProcesseor, ['@eXpansion\Framework\Core\Services\SymfonyEventAdapter']]

    eXpansion\Framework\Core\Services\Application\DispatcherInterface: '@eXpansion\Framework\Core\Services\Application\Dispatcher'


    eXpansion\Framework\Core\Services\SymfonyEventAdapter:
        class: eXpansion\Framework\Core\Services\SymfonyEventAdapter

    eXpansion\Framework\Core\Services\Application\DispatchLogger:
        class: eXpansion\Framework\Core\Services\Application\DispatchLogger

    eXpansion\Framework\Core\Services\PluginManager:
        class: "%expansion.service.plugin_manager.class%"

    eXpansion\Framework\Core\Services\DataProviderManager:
        class: "%expansion.service.data_provider_manager.class%"

    eXpansion\Framework\Core\Services\Console:
        class: "%expansion.service.console.class%"
        public: true
        arguments:
            - '%color_enabled%'

    eXpansion\Framework\Core\Services\ChatCommands:
        class: "%expansion.service.chat_commands.class%"
        arguments:
          - '%expansion.service.chat_commands.depth%'

    eXpansion\Framework\Core\Model\Plugin\PluginDescriptionFactory:
        class: 'eXpansion\Framework\Core\Model\Plugin\PluginDescriptionFactory'
        arguments:
            - 'eXpansion\Framework\Core\Model\Plugin\PluginDescription'

