<?php

namespace eXpansion\Bundle\Acme\Plugins\Gui;

use eXpansion\Framework\Core\Model\Gui\ManialinkInterface;
use eXpansion\Framework\Core\Model\Gui\Widget;
use eXpansion\Framework\Core\Plugins\Gui\WindowFactory as BaseWindowFactory;
use eXpansion\Framework\Gui\Components\Label;
use eXpansion\Framework\Gui\Components\Dropdown;
use FML\Script\ScriptLabel;

class WindowFactory extends BaseWindowFactory
{

    /**
     * @param ManialinkInterface|Widget $manialink
     */
    protected function createContent(ManialinkInterface $manialink)
    {
        parent::createContent($manialink);

        $lbl = $this->uiFactory->createLabel("update me", Label::TYPE_HEADER, "exp2_text");
        $manialink->addChild($lbl);

        $hash = MemoryWidgetFactory::$exp_hash;
        // next 2 methods would be generated by script manager
        $manialink->getFmlManialink()->getScript()->addCustomScriptLabel(ScriptLabel::OnInit,
            'declare Text '.$hash.' for LocalUser = "";
            declare Text '.$hash.'_check for LocalUser = "";
            declare Text '.$hash.'_oldCheck = "";           
            '
        );
        $manialink->getFmlManialink()->getScript()->addCustomScriptLabel(ScriptLabel::Loop,
            '
            if ('.$hash.'_check != '.$hash.'_oldCheck) {
                ---'.$hash.'---               
            }'
        );

        // this is what user needs to do for php part...
        $manialink->getFmlManialink()->getScript()->addCustomScriptLabel(
            $hash,
            '(Page.GetFirstChild("exp2_text") as CMlLabel).Value ='.$hash.';'
        );


    }

}
