services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Bundle\CustomUi\Plugins\Gui\CustomCheckpointWidget:
        class: eXpansion\Bundle\CustomUi\Plugins\Gui\CustomCheckpointWidget
        arguments:
          $name:  "Checkpoints"
          $posX: 0
          $posY: 0
          $sizeX: null
          $sizeY: null