services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # Data providers to handle the script waypoint callback and dispatch it in 3 distinctive events.
    #
    expansion.framework.game_trackmania.data_providers.waypoint:
        class: eXpansion\Framework\GameTrackmania\DataProviders\WayPointDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "tm.script.waypoint", interface: eXpansion\Framework\GameTrackmania\DataProviders\Listener\ListenerInterfaceWaypointData}
            - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.WayPoint, method: onWayPoint }

    expansion.framework.game_trackmania.data_providers.script_base_rounds.race:
        class: eXpansion\Framework\GameTrackmania\DataProviders\ScriptBaseRounds\RaceDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "tm.script.race", interface: eXpansion\Framework\GameTrackmania\DataProviders\Listener\ListenerInterfaceRaceData}
            - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.WayPoint, method: onWayPoint }

    expansion.framework.game_trackmania.data_providers.script_time_attack.race:
        class: eXpansion\Framework\GameTrackmania\DataProviders\ScriptTimeAttack\RaceDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "tm.script.race", interface: eXpansion\Framework\GameTrackmania\DataProviders\Listener\ListenerInterfaceRaceData}
            - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.WayPoint, method: onWayPoint }

    expansion.framework.game_trackmania.data_providers.lap:
        class: eXpansion\Framework\GameTrackmania\DataProviders\LapDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "tm.script.lap", interface: eXpansion\Framework\GameTrackmania\DataProviders\Listener\ListenerInterfaceLapData}
            - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.WayPoint, method: onWayPoint }

    #
    # Generic Data providers.
    #
    expansion.framework.game_trackmania.data_providers.player:
        class: eXpansion\Framework\GameTrackmania\DataProviders\PlayerEventsDataProvider
        tags:
            - {name: expansion.dataprovider, provider: "tm.script.player", interface: eXpansion\Framework\GameTrackmania\DataProviders\Listener\ListenerInterfacePlayerEvents}
            - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.StartLine, method: onStartLine}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.GiveUp, method: onGiveUp}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Event.Respawn, method: onRespawn}

    expansion.framework.game_trackmania.data_providers.method_get_scores:
        class: eXpansion\Framework\GameTrackmania\DataProviders\MethodGetScoresDataProvider
        tags:
            - {name: expansion.dataprovider, provider: 'mp.method.get_scores', interface: eXpansion\Framework\Core\ScriptMethods\AbstractScriptMethod}
            - {name: expansion.dataprovider.compatibility, title: TM}
            - {name: expansion.dataprovider.listener, event_name: Trackmania.Scores, method: setScores}

    expansion.framework.game_trackmania.data_providers.script_base_rounds.method_get_number_laps:
        class: eXpansion\Framework\GameTrackmania\DataProviders\ScriptBaseRounds\MethodGetNumberLapsDataProvider
        tags:
          - {name: expansion.dataprovider, provider: 'mp.method.get_number_laps', interface: eXpansion\Framework\Core\ScriptMethods\AbstractScriptMethod}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'rounds.script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'cup.script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'team.script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'chase.script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'laps.script.txt'}

    expansion.framework.game_trackmania.data_providers.script_time_attack.method_get_number_laps:
        class: eXpansion\Framework\GameTrackmania\DataProviders\ScriptTimeAttack\MethodGetNumberLapsDataProvider
        tags:
          - {name: expansion.dataprovider, provider: 'mp.method.get_number_laps', interface: eXpansion\Framework\Core\ScriptMethods\AbstractScriptMethod}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'teamattack.script.txt'}
          - {name: expansion.dataprovider.compatibility, title: TM, gamemode: script, script: 'timeattack.script.txt'}