services:
    eXpansionExperimantal\Bundle\WidgetBestRecords\Plugins\BestRecords:
        class:  eXpansionExperimantal\Bundle\WidgetBestRecords\Plugins\BestRecords
        autowire: true
        arguments:
                $players: '@expansion.framework.core.user_groups.players'
                $allPlayers: '@expansion.framework.core.user_groups.all_players'
        tags:
          - {name: 'expansion.plugin', data_provider: 'expansion.local_records.race|expansion.local_records.lap|expansion.dedimania'}
          - {name: 'expansion.plugin', data_provider: 'mp.legacy.map'}

    eXpansionExperimantal\Bundle\WidgetBestRecords\Plugins\Gui\BestRecordsWidgetFactory:
            class: eXpansionExperimantal\Bundle\WidgetBestRecords\Plugins\Gui\BestRecordsWidgetFactory
            autowire: true
            arguments:
                $name:  "BestRecords"
                $posX: 0
                $posY: 0
                $sizeX: null
                $sizeY: null
            tags:
              - {name: expansion.plugin, data_provider: exp.widget}