parameters:

services:
    expansion.emotes.plugins.chat_commands:
        class: eXpansion\Framework\Core\Model\ChatCommand\ChatCommandPlugin
        arguments:
            -
              - '@expansion.emotes.chat_command.gg'
              - '@expansion.emotes.chat_command.bb'
              - '@expansion.emotes.chat_command.thx'
        tags:
            - {name: 'expansion.plugin', data_provider: 'expansion.chat_command_data'}

    eXpansion\Bundle\Emotes\Plugins\MenuItems:
        class: eXpansion\Bundle\Emotes\Plugins\MenuItems
        tags:
            - {name: 'expansion.plugin', data_provider: 'exp.menu.items'}
            - {name: 'expansion.plugin.parent', parent: 'eXpansion\Bundle\Menu\Plugins\MenuItems'}