<?php

namespace eXpansion\Bundle\CustomUi\Plugins\Gui;

use eXpansion\Framework\Core\Model\Gui\ManialinkInterface;
use eXpansion\Framework\Core\Model\Gui\WidgetFactoryContext;
use eXpansion\Framework\Core\Plugins\Gui\WidgetFactory;
use eXpansion\Framework\Gui\Components\uiLabel;

class CustomCheckpointWidget extends WidgetFactory
{

    public function __construct($name,
        $sizeX,
        $sizeY,
        $posX,
        $posY,
        WidgetFactoryContext $context)
    {
        parent::__construct($name, $sizeX, $sizeY, $posX, $posY, $context);
    }

    protected function createContent(ManialinkInterface $manialink)
    {
        parent::createContent($manialink);

        $line = $this->uiFactory->createLayoutLine(0, 0);


        $lbl = $this->uiFactory->createLabel("00:00.000", uiLabel::TYPE_HEADER, "CurrentTime");



        $manialink->addChild($line);



    }

    protected function updateContent(ManialinkInterface $manialink)
    {
        parent::updateContent($manialink); // TODO: Change the autogenerated stub
    }


}
