<?php

namespace eXpansion\Bundle\CustomUi\Plugins\Gui;

use eXpansion\Framework\Core\Model\Gui\ManialinkInterface;
use eXpansion\Framework\Core\Model\Gui\Widget;
use eXpansion\Framework\Core\Model\Gui\WidgetFactoryContext;
use eXpansion\Framework\Core\Plugins\Gui\WidgetFactory;
use FML\Controls\Frame;
use FML\Script\ScriptLabel;

class FinishRecapWidget extends WidgetFactory
{

    const rowCount = 3;
    const columnCount = 6;

    public function __construct(
        $name,
        $sizeX,
        $sizeY,
        $posX,
        $posY,
        WidgetFactoryContext $context
    ) {
        parent::__construct($name, $sizeX, $sizeY, $posX, $posY, $context);
    }

    /**
     * @param ManialinkInterface|Widget $manialink
     */
    protected function createContent(ManialinkInterface $manialink)
    {
        parent::createContent($manialink);

        $frame = Frame::create("Frame_Main");
        $frame->setScale(1);
        $manialink->addChild($frame);

        $text = str_split("Race Finished!");

        $finish = Frame::create("FinishText");
        $manialink->addChild($frame);

        foreach ($text as $letter) {
            $lbl = $this->uiFactory->createLabel($letter);
            $lbl->setPosition(0, 6)->setAlign("center", "center")
                ->setSize(20, 4)->setTextSize(2)->setTextFont("RajdhaniMono")->addClass("uiFadedText");
            $finish->addChild($lbl);
        }

        $elementCount = 0;
        $rows = $this->uiFactory->createLayoutRow(0, 0, [], -1);

        for ($i = 0; $i < self::rowCount; $i++) {
            $elements = [];
            for ($c = 0; $c < self::columnCount; $c++) {
                $elements[] = $this->createColumnBox($elementCount);
                $elementCount++;
            }
            $line = $this->uiFactory->createLayoutLine(0, 0, $elements, 1);

            $rows->addChild($line);
        }


        $manialink->getFmlManialink()->getScript()->addScriptFunction("", <<<EOL
             Void HideResults() {        
                declare CMlFrame MainFrame = (Page.GetFirstChild("frame_Main") as CMlFrame);    
                MainFrame.Hide();                
             }
            
            Void ShowResults() {
                declare CMlFrame MainFrame = (Page.GetFirstChild("frame_Main") as CMlFrame);    
                declare CMlFrame frame = (Page.GetFirstChild("finish") as CMlFrame);
                declare CMlQuad background = (Page.GetFirstChild("background") as CMlQuad);
                
                MainFrame.Show();
                
                Page.GetClassChildren("fadedText", frame, True);
                declare Delay = 0;
                declare Real x = 0.;
                foreach (Label in Page.GetClassChildren_Result) {
                    if (Label != Null) {
                    declare elem = (Label as CMlLabel);
                        x += 4; 
                        Label.RelativePosition_V3.X = x;
                        AnimMgr.Add(Label, "<quad opacity=\"1.\" />", Now + Delay, 250, CAnimManager::EAnimManagerEasing::Linear);
                        Delay +=100;	
                    }
                }
            }
                                           
EOL
        );

        $manialink->getFmlManialink()->getScript()->addCustomScriptLabel(ScriptLabel::Loop,
            <<<EOL
    
         

EOL
        );

    }

    protected function updateContent(ManialinkInterface $manialink)
    {
        parent::updateContent($manialink); // TODO: Change the autogenerated stub
    }

    public function createColumnBox($index)
    {

        $width = 30;
        $height = 5;

        $label = $this->uiFactory->createLabel();
        $label->setAlign("left", "center");
        $label->setTextSize(1)->setPosition(1, -($height / 2));
        $label->setSize($width, $height)
            ->setId("Cp_".$index);

        return $label;
    }


}
