services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    eXpansion\Bundle\Dedimania\Services\DedimaniaService:
        class: eXpansion\Bundle\Dedimania\Services\DedimaniaService

    expansion.dedimania.data_providers.dedimania:
        class: eXpansion\Bundle\Dedimania\DataProviders\DedimaniaDataProvider
        tags:
          - {name: 'expansion.dataprovider', provider: "expansion.dedimania", interface: eXpansion\Bundle\Dedimania\DataProviders\Listener\DedimaniaDataListener}
          - {name: 'expansion.dataprovider.compatibility', title: 'TM'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.dedimania.records.load', method: 'onDedimaniaRecordsLoaded'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.dedimania.records.update', method: 'onDedimaniaRecordsUpdate'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.dedimania.player.connect', method: 'onDedimaniaPlayerConnect'}
          - {name: 'expansion.dataprovider.listener', event_name: 'expansion.dedimania.player.disconnect', method: 'onDedimaniaPlayerDisconnect'}